def runCommand(String labelText, String unixCommand, String windowsCommand = null) {
    if (isUnix()) {
        sh(label: labelText, script: unixCommand)
    } else {
        powershell(label: labelText, script: windowsCommand ?: unixCommand)
    }
}

def gatewayHealthUrl() {
    def rawUrl = params.GATEWAY_URL?.trim()
    if (!rawUrl) {
        rawUrl = params.DEPLOY_TARGET == 'kubernetes' ? 'http://localhost:30500' : 'http://localhost:5000'
    }

    return rawUrl.endsWith('/health') ? rawUrl : "${rawUrl}/health"
}

def randomSecret(String prefix, int length = 32) {
    def alphabet = ('A'..'Z').join() + ('a'..'z').join() + ('0'..'9').join()
    def random = new java.security.SecureRandom()
    def body = (1..length).collect { alphabet[random.nextInt(alphabet.length())] }.join()
    return "${prefix}_${body}!Aa1"
}

def generatedVagrantEnv() {
    def sqlPassword = randomSecret('sql')
    def mongoPassword = randomSecret('mongo')
    def neo4jPassword = randomSecret('neo4j')
    def rabbitPassword = randomSecret('rabbit')
    def jwtSecret = randomSecret('jwt', 48)
    def jwtRefreshSecret = randomSecret('jwtRefresh', 48)

    return """# Generated by Jenkins for local CI/CD demos.
# Replace with a Jenkins Secret File credential for shared or production-like use.

SQL_SERVER=192.168.56.10
SQL_PORT=1433
SQL_USERNAME=sa
SQL_PASSWORD=${sqlPassword}
SQL_DATABASE=LaylaCore
MSSQL_MEM_LIMIT=2048

MONGO_INITDB_ROOT_USERNAME=layla
MONGO_INITDB_ROOT_PASSWORD=${mongoPassword}
MONGO_PORT=27017

NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=${neo4jPassword}
NEO4J_BROWSER_PORT=7474
NEO4J_BOLT_PORT=7687

RABBIT_HostName=192.168.56.10
RABBIT_USER=layla
RABBIT_PASSWORD=${rabbitPassword}
RABBIT_PORT=5672
RABBIT_MANAGEMENT_PORT=15672

WORLDBUILDING_PORT_HTTP=3001
WORLDBUILDING_PORT_HTTPS=3000
WORLDBUILDING_ALLOWED_ORIGINS=http://192.168.56.12:5000,https://192.168.56.11:5288

CORE_PORT_HTTPS=7166
CORE_PORT_HTTP=5287
CORE_ENVIRONMENT=Production

WEB_PORT_HTTPS=5288
WEB_PORT_HTTP=5289

JWT_SECRET=${jwtSecret}
JWT_SECRET_REFRESH=${jwtRefreshSecret}
JWT_ISSUER=layla-core
JWT_AUDIENCE=layla-clients
JWT_ACCESS_TOKEN_EXPIRY=1440
JWT_REFRESH_TOKEN_EXPIRY=10080
"""
}

def generatedKubernetesSecret() {
    def sqlPassword = randomSecret('sql')
    def mongoPassword = randomSecret('mongo')
    def neo4jPassword = randomSecret('neo4j')
    def rabbitPassword = randomSecret('rabbit')
    def jwtSecret = randomSecret('jwt', 48)
    def jwtRefreshSecret = randomSecret('jwtRefresh', 48)

    return """apiVersion: v1
kind: Secret
metadata:
  name: layla-secrets
  namespace: layla
type: Opaque
stringData:
  sql-sa-password: "${sqlPassword}"
  sql-connection-string: "Server=sqlserver,1433;Database=LaylaCore;User Id=sa;Password=${sqlPassword};TrustServerCertificate=True;"
  mongo-root-username: "layla"
  mongo-root-password: "${mongoPassword}"
  mongo-connection-string: "mongodb://layla:${mongoPassword}@mongodb:27017/layla_worldbuilding?authSource=admin"
  neo4j-auth: "neo4j/${neo4jPassword}"
  neo4j-username: "neo4j"
  neo4j-password: "${neo4jPassword}"
  rabbit-user: "layla"
  rabbit-password: "${rabbitPassword}"
  rabbitmq-url: "amqp://layla:${rabbitPassword}@rabbitmq:5672"
  jwt-secret: "${jwtSecret}"
  jwt-refresh-secret: "${jwtRefreshSecret}"
  jwt-issuer: "layla-core"
  jwt-audience: "layla-clients"
  jwt-expiry-minutes: "1440"
  jwt-refresh-expiry: "10080"
  email-host: "smtp.demo.local"
  email-port: "587"
  email-username: "demo@layla.local"
  email-password: "demo-password-not-used"
  email-from-name: "Layla"
  email-from-email: "no-reply@layla.local"
"""
}

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '15'))
        disableConcurrentBuilds()
        timestamps()
    }

    parameters {
        choice(
            name: 'DEPLOY_TARGET',
            choices: ['vagrant-docker', 'kubernetes'],
            description: 'Destino de despliegue. vagrant-docker levanta VMs Ubuntu locales con Puppet y Docker Compose; kubernetes aplica deploy/k8s.'
        )
        booleanParam(
            name: 'RUN_DEPLOY',
            defaultValue: true,
            description: 'Si esta apagado, ejecuta solo restore, pruebas y build de imagenes.'
        )
        string(
            name: 'GATEWAY_URL',
            defaultValue: '',
            description: 'URL base para validar el gateway. Vacio usa http://localhost:5000 o http://localhost:30500 segun el destino.'
        )
        string(
            name: 'ENV_FILE_CREDENTIAL_ID',
            defaultValue: '',
            description: 'Opcional: ID de una credencial Jenkins tipo Secret File con deploy/vagrant/files/env/.env.shared.'
        )
    }

    environment {
        DOTNET_CLI_TELEMETRY_OPTOUT = '1'
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE = '1'
        CI = 'true'
    }

    stages {
        stage('Preflight') {
            steps {
                script {
                    runCommand(
                        'Check base tools',
                        '''
set -eu
dotnet --version
node --version
corepack --version
docker --version
docker compose version
''',
                        '''
$ErrorActionPreference = "Stop"
dotnet --version
node --version
corepack --version
docker --version
docker compose version
'''
                    )

                    if (params.RUN_DEPLOY && params.DEPLOY_TARGET == 'vagrant-docker') {
                        runCommand('Check Vagrant', 'vagrant --version', 'vagrant --version')
                    }

                    if (params.RUN_DEPLOY && params.DEPLOY_TARGET == 'kubernetes') {
                        runCommand(
                            'Check kubectl',
                            'kubectl version --client=true',
                            'kubectl version --client=true'
                        )
                    }
                }
            }
        }

        stage('Restore') {
            parallel {
                stage('server-core') {
                    steps {
                        runCommand(
                            'Restore server-core',
                            'dotnet restore src/server-core/Layla.Core.slnx',
                            'dotnet restore src/server-core/Layla.Core.slnx'
                        )
                    }
                }
                stage('api-gateway') {
                    steps {
                        runCommand(
                            'Restore api-gateway',
                            'dotnet restore src/api-gateway/api-gateway.sln',
                            'dotnet restore src/api-gateway/api-gateway.sln'
                        )
                    }
                }
                stage('client-web') {
                    steps {
                        runCommand(
                            'Restore client-web',
                            'dotnet restore src/client-web/client-web.sln',
                            'dotnet restore src/client-web/client-web.sln'
                        )
                        runCommand(
                            'Restore client-web tests',
                            'dotnet restore src/client-web.Tests/client-web.Tests.csproj',
                            'dotnet restore src/client-web.Tests/client-web.Tests.csproj'
                        )
                    }
                }
                stage('server-worldbuilding') {
                    steps {
                        dir('src/server-worldbuilding') {
                            runCommand(
                                'Install server-worldbuilding packages',
                                'corepack pnpm install --frozen-lockfile',
                                'corepack pnpm install --frozen-lockfile'
                            )
                        }
                    }
                }
                stage('client-web assets') {
                    steps {
                        dir('src/client-web') {
                            runCommand(
                                'Install client-web packages',
                                'corepack pnpm install --frozen-lockfile',
                                'corepack pnpm install --frozen-lockfile'
                            )
                        }
                    }
                }
            }
        }

        stage('Unit Tests') {
            parallel {
                stage('server-core tests') {
                    steps {
                        runCommand(
                            'Run server-core tests',
                            'dotnet test src/server-core/Layla.Core.Tests/Layla.Core.Tests.csproj --configuration Release --logger "trx;LogFileName=server-core.trx" --results-directory TestResults/server-core',
                            'dotnet test src/server-core/Layla.Core.Tests/Layla.Core.Tests.csproj --configuration Release --logger "trx;LogFileName=server-core.trx" --results-directory TestResults/server-core'
                        )
                    }
                }
                stage('client-web tests') {
                    steps {
                        runCommand(
                            'Run client-web tests',
                            'dotnet test src/client-web.Tests/client-web.Tests.csproj --configuration Release --logger "trx;LogFileName=client-web.trx" --results-directory TestResults/client-web',
                            'dotnet test src/client-web.Tests/client-web.Tests.csproj --configuration Release --logger "trx;LogFileName=client-web.trx" --results-directory TestResults/client-web'
                        )
                    }
                }
                stage('worldbuilding tests') {
                    steps {
                        dir('src/server-worldbuilding') {
                            runCommand(
                                'Run worldbuilding tests',
                                'corepack pnpm test',
                                'corepack pnpm test'
                            )
                        }
                    }
                }
            }
        }

        stage('Build') {
            parallel {
                stage('server-core build') {
                    steps {
                        runCommand(
                            'Build server-core',
                            'dotnet build src/server-core/Layla.Core.slnx --configuration Release --no-restore',
                            'dotnet build src/server-core/Layla.Core.slnx --configuration Release --no-restore'
                        )
                    }
                }
                stage('api-gateway build') {
                    steps {
                        runCommand(
                            'Build api-gateway',
                            'dotnet build src/api-gateway/api-gateway.sln --configuration Release --no-restore',
                            'dotnet build src/api-gateway/api-gateway.sln --configuration Release --no-restore'
                        )
                    }
                }
                stage('client-web build') {
                    steps {
                        dir('src/client-web') {
                            runCommand(
                                'Build client-web frontend',
                                'corepack pnpm run build:frontend',
                                'corepack pnpm run build:frontend'
                            )
                        }
                        runCommand(
                            'Build client-web',
                            'dotnet build src/client-web/client-web.sln --configuration Release --no-restore',
                            'dotnet build src/client-web/client-web.sln --configuration Release --no-restore'
                        )
                    }
                }
                stage('worldbuilding build') {
                    steps {
                        dir('src/server-worldbuilding') {
                            runCommand(
                                'Build server-worldbuilding',
                                'corepack pnpm run build',
                                'corepack pnpm run build'
                            )
                        }
                    }
                }
            }
        }

        stage('Docker Images') {
            steps {
                script {
                    runCommand(
                        'Build Docker images',
                        '''
set -eu
docker build -t layla-server-core:latest -f src/server-core/Layla.Api/Dockerfile src/server-core
docker build -t layla-worldbuilding:latest src/server-worldbuilding
docker build -t layla-api-gateway:latest src/api-gateway
docker build -t layla-client-web:latest -f src/client-web/Dockerfile src
''',
                        '''
$ErrorActionPreference = "Stop"
docker build -t layla-server-core:latest -f src/server-core/Layla.Api/Dockerfile src/server-core
docker build -t layla-worldbuilding:latest src/server-worldbuilding
docker build -t layla-api-gateway:latest src/api-gateway
docker build -t layla-client-web:latest -f src/client-web/Dockerfile src
'''
                    )
                }
            }
        }

        stage('Prepare Deployment Config') {
            when {
                expression { params.RUN_DEPLOY }
            }
            steps {
                script {
                    if (params.DEPLOY_TARGET == 'vagrant-docker') {
                        def envPath = 'deploy/vagrant/files/env/.env.shared'
                        if (params.ENV_FILE_CREDENTIAL_ID?.trim()) {
                            withCredentials([file(credentialsId: params.ENV_FILE_CREDENTIAL_ID.trim(), variable: 'LAYLA_ENV_FILE')]) {
                                runCommand(
                                    'Install Vagrant env from Jenkins credential',
                                    'install -m 600 "$LAYLA_ENV_FILE" deploy/vagrant/files/env/.env.shared',
                                    'Copy-Item -Force $env:LAYLA_ENV_FILE deploy/vagrant/files/env/.env.shared'
                                )
                            }
                        } else if (!fileExists(envPath)) {
                            writeFile(file: envPath, text: generatedVagrantEnv())
                        }

                        def envText = readFile(envPath)
                        if (envText.contains('CHANGE_ME')) {
                            error("${envPath} still contains CHANGE_ME placeholders. Provide a Secret File credential or let Jenkins generate a local demo file.")
                        }
                    }

                    if (params.DEPLOY_TARGET == 'kubernetes') {
                        writeFile(file: 'deploy/k8s/.generated-secret.yaml', text: generatedKubernetesSecret())
                    }
                }
            }
        }

        stage('Deploy') {
            when {
                expression { params.RUN_DEPLOY }
            }
            steps {
                script {
                    if (params.DEPLOY_TARGET == 'vagrant-docker') {
                        dir('deploy/vagrant') {
                            runCommand(
                                'Provision local Linux VMs with Puppet',
                                'vagrant up data apps edge --provision',
                                'vagrant up data apps edge --provision'
                            )
                            runCommand('Vagrant status', 'vagrant status', 'vagrant status')
                        }
                    }

                    if (params.DEPLOY_TARGET == 'kubernetes') {
                        runCommand(
                            'Apply Kubernetes manifests',
                            '''
set -eu
kubectl apply -f deploy/k8s/00-namespace.yaml
kubectl apply -f deploy/k8s/.generated-secret.yaml
kubectl apply -f deploy/k8s/02-sqlserver.yaml
kubectl apply -f deploy/k8s/03-mongodb.yaml
kubectl apply -f deploy/k8s/04-neo4j.yaml
kubectl apply -f deploy/k8s/05-rabbitmq.yaml
kubectl apply -f deploy/k8s/06-server-core.yaml
kubectl apply -f deploy/k8s/07-server-worldbuilding.yaml
kubectl apply -f deploy/k8s/08-api-gateway.yaml
kubectl apply -f deploy/k8s/09-client-web.yaml
''',
                            '''
$ErrorActionPreference = "Stop"
kubectl apply -f deploy/k8s/00-namespace.yaml
kubectl apply -f deploy/k8s/.generated-secret.yaml
kubectl apply -f deploy/k8s/02-sqlserver.yaml
kubectl apply -f deploy/k8s/03-mongodb.yaml
kubectl apply -f deploy/k8s/04-neo4j.yaml
kubectl apply -f deploy/k8s/05-rabbitmq.yaml
kubectl apply -f deploy/k8s/06-server-core.yaml
kubectl apply -f deploy/k8s/07-server-worldbuilding.yaml
kubectl apply -f deploy/k8s/08-api-gateway.yaml
kubectl apply -f deploy/k8s/09-client-web.yaml
'''
                        )
                    }
                }
            }
        }

        stage('Smoke Test') {
            when {
                expression { params.RUN_DEPLOY }
            }
            steps {
                script {
                    if (params.DEPLOY_TARGET == 'kubernetes') {
                        runCommand(
                            'Wait for Kubernetes rollout',
                            '''
set -eu
kubectl rollout status statefulset/sqlserver -n layla --timeout=300s
kubectl rollout status statefulset/mongodb -n layla --timeout=300s
kubectl rollout status statefulset/neo4j -n layla --timeout=300s
kubectl rollout status statefulset/rabbitmq -n layla --timeout=300s
kubectl rollout status deployment/server-core -n layla --timeout=300s
kubectl rollout status deployment/layla-worldbuilding -n layla --timeout=300s
kubectl rollout status deployment/layla-api-gateway -n layla --timeout=300s
kubectl rollout status deployment/layla-web -n layla --timeout=300s
''',
                            '''
$ErrorActionPreference = "Stop"
kubectl rollout status statefulset/sqlserver -n layla --timeout=300s
kubectl rollout status statefulset/mongodb -n layla --timeout=300s
kubectl rollout status statefulset/neo4j -n layla --timeout=300s
kubectl rollout status statefulset/rabbitmq -n layla --timeout=300s
kubectl rollout status deployment/server-core -n layla --timeout=300s
kubectl rollout status deployment/layla-worldbuilding -n layla --timeout=300s
kubectl rollout status deployment/layla-api-gateway -n layla --timeout=300s
kubectl rollout status deployment/layla-web -n layla --timeout=300s
'''
                        )
                    }

                    retry(30) {
                        sleep(time: 10, unit: 'SECONDS')
                        runCommand(
                            'Gateway health',
                            "curl -fsS ${gatewayHealthUrl()}",
                            "curl.exe -fsS ${gatewayHealthUrl()}"
                        )
                    }

                    if (params.DEPLOY_TARGET == 'vagrant-docker') {
                        dir('deploy/vagrant') {
                            runCommand(
                                'Show Vagrant containers',
                                '''
set -eu
vagrant ssh data -c "sudo docker compose -f /srv/layla/compose.yml ps"
vagrant ssh apps -c "sudo docker compose -f /srv/layla/compose.yml ps"
vagrant ssh edge -c "sudo docker compose -f /srv/layla/compose.yml ps"
''',
                                '''
$ErrorActionPreference = "Stop"
vagrant ssh data -c "sudo docker compose -f /srv/layla/compose.yml ps"
vagrant ssh apps -c "sudo docker compose -f /srv/layla/compose.yml ps"
vagrant ssh edge -c "sudo docker compose -f /srv/layla/compose.yml ps"
'''
                            )
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'TestResults/**/*', allowEmptyArchive: true
        }
        cleanup {
            script {
                if (fileExists('deploy/k8s/.generated-secret.yaml')) {
                    if (isUnix()) {
                        sh 'rm -f deploy/k8s/.generated-secret.yaml'
                    } else {
                        powershell 'Remove-Item -Force deploy/k8s/.generated-secret.yaml'
                    }
                }
            }
        }
    }
}
