#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Renders the .env consumed by deploy/docker/docker-compose.yml for a
# single-host deployment (every service runs on ONE local Linux server and
# talks over the compose network, so hosts are service names, not VM IPs).
#
# Values are taken from the environment (injected from GitHub Secrets in CI).
# Any password left unset is auto-generated with a strong, non-production
# demo value, mirroring the behaviour of the Jenkins pipeline.
#
# Usage: deploy/github-actions/generate-env.sh [output-path]
#        (defaults to deploy/docker/.env)
# ---------------------------------------------------------------------------
set -euo pipefail

ENV_FILE="${1:-deploy/docker/.env}"

rand() {
  # URL/shell-safe random alphanumeric string of the requested length.
  # Reads a bounded chunk of /dev/urandom via process substitution so `tr`
  # never receives SIGPIPE (which would trip `set -o pipefail`).
  local n="${1:-24}"
  local out
  out=$(LC_ALL=C tr -dc 'A-Za-z0-9' < <(head -c "$(( n * 8 ))" /dev/urandom))
  printf '%s' "${out:0:n}"
}

strong() {
  # prefix + random body + fixed suffix guarantees upper/lower/digit/symbol
  # and minimum length, satisfying SQL Server password complexity rules.
  printf '%s_%s!Aa1' "$1" "$(rand 24)"
}

# --- Secrets: use the injected value, otherwise generate a demo one ---------
SQL_PASSWORD="${SQL_PASSWORD:-$(strong sql)}"
MONGO_INITDB_ROOT_PASSWORD="${MONGO_INITDB_ROOT_PASSWORD:-$(strong mongo)}"
NEO4J_PASSWORD="${NEO4J_PASSWORD:-$(strong neo4j)}"
RABBIT_PASSWORD="${RABBIT_PASSWORD:-$(strong rabbit)}"
JWT_SECRET="${JWT_SECRET:-$(rand 48)}"
JWT_SECRET_REFRESH="${JWT_SECRET_REFRESH:-$(rand 48)}"

# --- Non-secret defaults (overridable from the environment) -----------------
SQL_USERNAME="${SQL_USERNAME:-sa}"
SQL_DATABASE="${SQL_DATABASE:-LaylaCore}"
SQL_PORT="${SQL_PORT:-1433}"
SQL_MEM_LIMIT="${SQL_MEM_LIMIT:-2048}"

MONGO_INITDB_ROOT_USERNAME="${MONGO_INITDB_ROOT_USERNAME:-layla}"
MONGO_PORT="${MONGO_PORT:-27017}"

NEO4J_USERNAME="${NEO4J_USERNAME:-neo4j}"
NEO4J_BROWSER_PORT="${NEO4J_BROWSER_PORT:-7474}"
NEO4J_BOLT_PORT="${NEO4J_BOLT_PORT:-7687}"

RABBIT_USER="${RABBIT_USER:-layla}"
RABBIT_PORT="${RABBIT_PORT:-5672}"
RABBIT_MANAGEMENT_PORT="${RABBIT_MANAGEMENT_PORT:-15672}"
RABBIT_EXCHANGE="${RABBIT_EXCHANGE:-worldbuilding.events}"
RABBIT_QUEUE="${RABBIT_QUEUE:-worldbuilding.node.queue}"

WORLDBUILDING_PORT_HTTP="${WORLDBUILDING_PORT_HTTP:-3001}"
WORLDBUILDING_PORT_HTTPS="${WORLDBUILDING_PORT_HTTPS:-3000}"
WORLDBUILDING_ALLOWED_ORIGINS="${WORLDBUILDING_ALLOWED_ORIGINS:-http://localhost:5000,https://localhost:5288}"

CORE_PORT_HTTPS="${CORE_PORT_HTTPS:-7166}"
CORE_PORT_HTTP="${CORE_PORT_HTTP:-5287}"
CORE_ENVIRONMENT="${CORE_ENVIRONMENT:-Production}"

WEB_PORT_HTTPS="${WEB_PORT_HTTPS:-5288}"
WEB_PORT_HTTP="${WEB_PORT_HTTP:-5289}"

JWT_ISSUER="${JWT_ISSUER:-layla-core}"
JWT_AUDIENCE="${JWT_AUDIENCE:-layla-clients}"
JWT_ACCESS_TOKEN_EXPIRY="${JWT_ACCESS_TOKEN_EXPIRY:-1440}"
JWT_REFRESH_TOKEN_EXPIRY="${JWT_REFRESH_TOKEN_EXPIRY:-10080}"

# SMTP is required by Secrets.cs but unused in demos; safe dummy values.
EMAIL_HOST="${EMAIL_HOST:-smtp.demo.local}"
EMAIL_PORT="${EMAIL_PORT:-587}"
EMAIL_USERNAME="${EMAIL_USERNAME:-demo@layla.local}"
EMAIL_PASSWORD="${EMAIL_PASSWORD:-demo-password-not-used}"
EMAIL_FROM_NAME="${EMAIL_FROM_NAME:-Layla}"
EMAIL_FROM_EMAIL="${EMAIL_FROM_EMAIL:-no-reply@layla.local}"

# Single host: services reach each other by compose service name.
SQL_SERVER="${SQL_SERVER:-sqlserver}"
RABBIT_HostName="${RABBIT_HostName:-rabbitmq}"

mkdir -p "$(dirname "$ENV_FILE")"

cat > "$ENV_FILE" <<EOF
# =====================================================================
# Generated by deploy/github-actions/generate-env.sh
# Single-host Docker Compose deployment for the Layla GitHub Actions CD.
# Do NOT commit this file. Replace the demo passwords with GitHub Secrets
# for any shared or production-like server.
# =====================================================================

# --- SQL Server ---
SQL_SERVER=${SQL_SERVER}
SQL_PORT=${SQL_PORT}
SQL_USERNAME=${SQL_USERNAME}
SQL_PASSWORD=${SQL_PASSWORD}
SQL_DATABASE=${SQL_DATABASE}
SQL_MEM_LIMIT=${SQL_MEM_LIMIT}

# --- MongoDB ---
MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
MONGO_PORT=${MONGO_PORT}

# --- Neo4j ---
NEO4J_USERNAME=${NEO4J_USERNAME}
NEO4J_PASSWORD=${NEO4J_PASSWORD}
NEO4J_BROWSER_PORT=${NEO4J_BROWSER_PORT}
NEO4J_BOLT_PORT=${NEO4J_BOLT_PORT}

# --- RabbitMQ ---
RABBIT_HostName=${RABBIT_HostName}
RABBIT_USER=${RABBIT_USER}
RABBIT_PASSWORD=${RABBIT_PASSWORD}
RABBIT_PORT=${RABBIT_PORT}
RABBIT_MANAGEMENT_PORT=${RABBIT_MANAGEMENT_PORT}
RABBIT_EXCHANGE=${RABBIT_EXCHANGE}
RABBIT_QUEUE=${RABBIT_QUEUE}

# --- Worldbuilding (Node.js) ---
WORLDBUILDING_PORT_HTTP=${WORLDBUILDING_PORT_HTTP}
WORLDBUILDING_PORT_HTTPS=${WORLDBUILDING_PORT_HTTPS}
WORLDBUILDING_ALLOWED_ORIGINS=${WORLDBUILDING_ALLOWED_ORIGINS}

# --- Core API (.NET) ---
CORE_PORT_HTTPS=${CORE_PORT_HTTPS}
CORE_PORT_HTTP=${CORE_PORT_HTTP}
CORE_ENVIRONMENT=${CORE_ENVIRONMENT}

# --- Web client (.NET) ---
WEB_PORT_HTTPS=${WEB_PORT_HTTPS}
WEB_PORT_HTTP=${WEB_PORT_HTTP}

# --- JWT ---
JWT_SECRET=${JWT_SECRET}
JWT_SECRET_REFRESH=${JWT_SECRET_REFRESH}
JWT_ISSUER=${JWT_ISSUER}
JWT_AUDIENCE=${JWT_AUDIENCE}
JWT_ACCESS_TOKEN_EXPIRY=${JWT_ACCESS_TOKEN_EXPIRY}
JWT_REFRESH_TOKEN_EXPIRY=${JWT_REFRESH_TOKEN_EXPIRY}

# --- Email (SMTP) — required by Secrets.cs, unused in demos ---
EMAIL_HOST=${EMAIL_HOST}
EMAIL_PORT=${EMAIL_PORT}
EMAIL_USERNAME=${EMAIL_USERNAME}
EMAIL_PASSWORD=${EMAIL_PASSWORD}
EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
EMAIL_FROM_EMAIL=${EMAIL_FROM_EMAIL}
EOF

echo "Wrote $ENV_FILE"
